# Generated by Django 5.2.14 on 2026-06-15 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_full_name', models.CharField(blank=True, max_length=50)),
                ('shipping_country', models.CharField(blank=True, default='IRAN', max_length=25)),
                ('shipping_city', models.CharField(blank=True, max_length=25)),
                ('shipping_state', models.CharField(blank=True, max_length=25)),
                ('shipping_address', models.CharField(blank=True, max_length=250)),
                ('shipping_zipcode', models.CharField(blank=True, max_length=25)),
                ('shipping_phone', models.CharField(blank=True, max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shipping Address',
            },
        ),
    ]
