# Generated by Django 5.2.14 on 2026-06-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', ' در انتظار پرداخت '), ('Processing', ' در حال پردازش '), ('Shipped', ' ارسال شده به پست '), ('Delivered', ' تحویل داده شده ')], default='Pending', max_length=50),
        ),
    ]
