# Generated by Django 5.2.14 on 2026-06-17 15:15

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
