# Generated by Django 5.2.14 on 2026-05-16 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_star_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 5, 16, 12, 20, 41, 372620)),
        ),
    ]
