# Generated by Django 5.2.14 on 2026-06-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
